<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'INFOBEANS3_GUTUNBERG_JS', 'gutunberg.js' );
define( 'INFOBEANS3_GUTUNBERG_CSS', 'gutunberg.css' );

