<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'INFOBEANS_GUTENBERG_JS', 'gutenberg.js' );
define( 'INFOBEANS_PACKAGES_JS', 'packages.js' );
define( 'INFOBEANS_GUTENBERG_CSS', 'gutenberg.css' );

