version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18.16.0

    steps:
      - checkout
      
        - run:
          name: Navigate to ibtheme folder
          command: cd wp-content/themes/infobeans

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Compile Code
          command: npm run build

     

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

