version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Compile SCSS
          command: npm run build:scss

      - run:
          name: Compile JS
          command: npm run build:js

      - deploy:
          name: Deploy to WP VIP
          command: |
            wp vip update

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
