version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Compile Code
          command: npm run build

     

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

