# PHP CircleCI 2.0 configuration file.
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Pick a base image which matches the version of Node you need for
      # building from https://hub.docker.com/r/circleci/node/tags/
      #
      # Note: If using a different container, make sure it contains at least
      # git 2.6.0. (Use -stretch for circleci/node containers.)
      #- image: circleci/node:6.11-stretch # change version
      #- image: cimg/node:12.18.2
      - image: cimg/php:8.0.24-node


      #- image: circleci/php:7.3-node-browsers # need to check if need to change
    branches:
      # Don't build from a branch with the `-built` suffix, to
      # prevent endless loops of deploy scripts.
      ignore:
        - /^.*-built$/
    steps:
      - checkout
      - run:
          name: "Run builds" # change condition - Use IN
          no_output_timeout: 30m
          command: |
           ./private/bin/create_build.sh              
           