<?php
/**
 * File used to contain constant veriables.
 *
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 * @package infobeans-2023
 */

define( 'INFOBEANS_2023_GUTENBERG_JS', 'gutenberg.js' );
define( 'INFOBEANS_2023_PACKAGES_JS', 'packages.js' );
define( 'INFOBEANS_2023_GUTENBERG_CSS', 'gutenberg.css' );

